CORCI-986 build: Update SLES15.2 mpi include path
daos-stack/hdf5 pull request #14
Opened 2020-08-24 22:06 UTC by mjean308

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

2020-08-25 14:13 UTC, phender approved these changes

2020-08-25 14:55 UTC, brianjmurrell requested changes
Seems like there is a lot of `%if (0%{?suse_version} >= 1500) ... %else` branching.  Can this not be eliminated with more macros defined in lines 335-341?

2020-08-25 14:55 UTC, brianjmurrell commented on hdf5.spec
> +
```suggestion
```

2020-08-26 15:13 UTC, brianjmurrell approved these changes

2020-08-26 16:05 UTC, merged